export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './mealPlan.service';
import { MealPlanService } from './mealPlan.service';
export * from './person.service';
import { PersonService } from './person.service';
export * from './vapidPublicKey.service';
import { VapidPublicKeyService } from './vapidPublicKey.service';
export * from './vapidSubscription.service';
import { VapidSubscriptionService } from './vapidSubscription.service';
export const APIS = [IdentityService, LocationService, MealPlanService, PersonService, VapidPublicKeyService, VapidSubscriptionService];
